### ISSUE TITLE
brittany as invoked by vscode-hie-server doesn't match local machine, formats badly

### ISSUE THREAD

**Issue by jlebar** [alanz/vscode-hie-server#229]
I am finding that vscode-hie-server is formatting my code differently than when I invoke `brittany` locally.

Here's me invoking it locally:
```
$ brittany --version
brittany version 0.12.1.1
[snip]

$ brittany test.hs
f :: [String] -> Int
f (nm : cats : edges) =
  let edges' =
          map ((\[a, b] -> (a, [b])) . (map read . words)) edges :: [(Int, [Int])]
  in  0
```

In contrast, when I format from the command palette, I get something way worse:
```
f :: [String] -> Int
f (nm : cats : edges) =
    let edges' =
                map ((\[a, b] -> (a, [b])) . (map read . words)) edges :: [ ( Int
                      , [Int]
                      )
                    ]
    in  0
```

I am not sure what's going wrong here.  Is vscode-hie-server invoking a rogue version of brittany on my machine?  Could be.  I tried all of the brittany binaries in `~/.stack` and they had the first formatting, `find ~/.stack -name brittany | xargs -n1 -I{} sh -c '{} test.hs'`.

**Comment by fendor** [comment]
`vscode-hie-server` is compiled with its own brittany version, namely brittany-0.12.1.1.
Maybe we are not picking up every configuration on your system?

**Comment by jlebar** [comment]
Hi, thanks for your reply!

> Maybe we are not picking up every configuration on your system?

I do have a `~/.config/brittany/config.yaml`.  That's the only config.yaml or brittany.yaml anywhere in my home directory.  I didn't create this; the tool must have defaulted it.

Here's what's inside.

```
conf_debug:
  dconf_roundtrip_exactprint_only: false
  dconf_dump_bridoc_simpl_par: false
  dconf_dump_ast_unknown: false
  dconf_dump_bridoc_simpl_floating: false
  dconf_dump_config: false
  dconf_dump_bridoc_raw: false
  dconf_dump_bridoc_final: false
  dconf_dump_bridoc_simpl_alt: false
  dconf_dump_bridoc_simpl_indent: false
  dconf_dump_annotations: false
  dconf_dump_bridoc_simpl_columns: false
  dconf_dump_ast_full: false
conf_forward:
  options_ghc: []
conf_errorHandling:
  econf_ExactPrintFallback: ExactPrintFallbackModeInline
  econf_Werror: false
  econf_omit_output_valid_check: false
  econf_produceOutputOnErrors: false
conf_preprocessor:
  ppconf_CPPMode: CPPModeAbort
  ppconf_hackAroundIncludes: false
conf_obfuscate: false
conf_roundtrip_exactprint_only: false
conf_version: 1
conf_layout:
  lconfig_reformatModulePreamble: true
  lconfig_altChooser:
    tag: AltChooserBoundedSearch
    contents: 3
  lconfig_allowSingleLineExportList: false
  lconfig_importColumn: 50
  lconfig_hangingTypeSignature: false
  lconfig_importAsColumn: 50
  lconfig_alignmentLimit: 30
  lconfig_allowHangingQuasiQuotes: true
  lconfig_indentListSpecial: true
  lconfig_indentAmount: 2
  lconfig_alignmentBreakOnMultiline: true
  lconfig_experimentalSemicolonNewlines: false
  lconfig_cols: 80
  lconfig_indentPolicy: IndentPolicyFree
  lconfig_indentWhereSpecial: true
  lconfig_columnAlignMode:
    tag: ColumnAlignModeMajority
    contents: 0.7
```
