### ISSUE TITLE
[Documentation] new project setup

### ISSUE THREAD

**Issue by KristianBalaj** [alanz/vscode-hie-server#490]
It is hard to find out how to make the plugin work for a beginner.

I needed to check out my previous projects to find out that I need to create a `hie.yaml` file with following lines to make the plugin work.

```yaml
cradle:
  cabal:
    - path: './src'
      component: 'proj:exe:proj'
```

This should be written in the plugin documentation.
